KKUMTEUL/KKUMTEUL-backend

src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
src/test/java/com/kkumteul/domain/childprofile/repository/CumulativeMBTIScoreRepositoryTest.java
src/test/java/com/kkumteul/domain/childprofile/repository/GenreScoreRepositoryTest.java
src/test/java/com/kkumteul/domain/childprofile/repository/TopicScoreRepositoryTest.java
src/test/java/com/kkumteul/domain/childprofile/service/ChildProfileServiceTest.java
src/test/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepositoryTest.java
src/test/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryServiceTest.java
src/test/java/com/kkumteul/domain/mbti/repository/MBTIRepositoryTest.java
src/test/java/com/kkumteul/domain/mbti/service/MBTIServiceTest.java
src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
src/test/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeTest.java

> ex) #22 
> 테스트 코드 작성 예정
MBTI 설문 관련 기능 닫힌 PR에 리뷰 많이 남겨주세요. 문제가 많아요.

Test: MBTI 설문 관련 테스트 코드 작성

---

src/main/java/com/kkumteul/domain/user/controller/UserController.java
src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java
src/main/java/com/kkumteul/domain/user/dto/UserUpdateRequestDto.java
src/main/java/com/kkumteul/domain/user/entity/User.java
src/main/java/com/kkumteul/domain/user/service/UserService.java
src/main/java/com/kkumteul/exception/handler/GlobalExceptionHandler.java
src/test/java/com/kkumteul/domain/user/repository/UserRepositoryTest.java

> #30
> 유저 정보 수정에서 이미지 관련 리팩토링 진행중

Refactor 프로필 이미지 multipart

---

src/main/java/com/kkumteul/domain/survey/dto/SurveyResultDto.java
src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java

UI에 맞게 데이터 전송하도록 ChildProfile 정보 제공

Fix: UI에 맞게 데이터를 전송하도록 수정

---

src/main/java/com/kkumteul/domain/user/controller/UserController.java
src/main/java/com/kkumteul/domain/user/service/UserService.java

> #51
> 특정 유저의 자녀 프로필 검증 API 구현

Feat: 자녀 프로필 검증 API 구현

---

src/test/java/com/kkumteul/domain/book/controller/BookControllerTest.java
src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
src/test/java/com/kkumteul/domain/book/service/BookServiceTest.java

Feat: 빈 DB로 테스트 코드 실행

---

build.gradle
src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
src/main/java/com/kkumteul/domain/survey/controller/SurveyController.java
src/main/java/com/kkumteul/domain/survey/dto/SurveyResultRequestDto.java
src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacade.java
src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java

Refactor: 이벤트 로직 개선

---

src/main/java/com/kkumteul/domain/event/controller/EventController.java
src/main/java/com/kkumteul/domain/event/dto/EventDto.java
src/main/java/com/kkumteul/domain/event/repository/EventRepository.java
src/main/java/com/kkumteul/domain/event/service/EventService.java
src/main/java/com/kkumteul/filter/LoginFilter.java

Fix: 메인페이지 현재 진행중인 이벤트 조회 API 구현

---

src/main/java/com/kkumteul/domain/event/controller/EventController.java

> #71
> 이벤트 요청 userId JWT 방식으로 변경

Refactor: userId JWT 방식으로 변경

---

build.gradle
src/main/java/com/kkumteul/config/RedisConfig.java
src/main/java/com/kkumteul/domain/event/service/EventService.java

> #56
> Lua script 및 Redisson 사용하여 동시성 제어

Refactor: refactor event logic

---

src/main/java/com/kkumteul/domain/book/controller/BookController.java
src/main/java/com/kkumteul/domain/book/dto/GetLikeStatusResponse.java
src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
src/main/java/com/kkumteul/domain/book/service/BookService.java
src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java

> ex) #79
> 프론트에서 좋아요/싫어요 상태를 반영하기 위해 만든 로직입니다.

Feat: 좋아요 상태 조회 추가

---

src/main/java/com/kkumteul/domain/book/repository/BookRepository.java

> #85 
> 기본 추천 로직 성능 개선
전 - 1470
후 - 160
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Fix: 기본 추천 로직 성능 개선

---

src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileDto.java
src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileInsertRequestDto.java
src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
src/main/java/com/kkumteul/domain/user/entity/User.java
src/main/java/com/kkumteul/domain/user/service/UserService.java

> #78
> 유저 정보 수정 시 비밀번호 암호화 적용
> 자녀 프로필 추가 시 스코어 초기화 추가
> 자녀 프로필 리스트 반환값에 자녀 프로필 사진 추가

Refactor: 마이페이지 리팩토링 작업

---

build.gradle
src/test/java/com/kkumteul/domain/book/controller/BookControllerTest.java
src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
src/test/java/com/kkumteul/domain/book/service/BookServiceTest.java

> ex) 
> `@WithMockUser` 붙여서 해결했습니다.

Test: jwt 이후 테스트 코드 수정

---

src/main/java/com/kkumteul/config/SecurityConfig.java
src/test/java/com/kkumteul/batch/ChangePersonalityBatchConfigTest.java
src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
src/test/java/com/kkumteul/domain/code/controller/CommonCodeControllerTest.java
src/test/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryControllerTest.java
src/test/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryServiceTest.java
src/test/java/com/kkumteul/domain/recommendation/controller/RecommendationControllerTest.java
src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java

> ex) #91
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Fix: Security 도입으로 인한 테스트 실패 부분 수정

---

src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java

Fix: 유저 정보 반환값 수정

---

src/main/java/com/kkumteul/domain/event/controller/EventController.java
src/main/java/com/kkumteul/domain/event/dto/EventResultResponseDto.java
src/main/java/com/kkumteul/domain/event/repository/JoinEventRepository.java
src/main/java/com/kkumteul/domain/event/service/JoinEventService.java

Feat: 이벤트 당첨 결과 반환 API 구현

---

src/main/java/com/kkumteul/domain/book/repository/BookRepository.java

> ex) #98
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: 도서 검색 쿼리문 피드백 반영

---

src/test/java/com/kkumteul/domain/adminbook/controller/AdminBookControllerTest.java

>  #12
> 시큐리티 도입 내용 도서관리 테스트 코드에 반영
이렇게 하는게 맞나요?

Test: 시큐리티 도입 후 도서관리테스트 수정

---

src/main/java/com/kkumteul/domain/event/controller/AdminEventController.java
src/main/java/com/kkumteul/domain/event/entity/Event.java
src/main/java/com/kkumteul/domain/event/repository/EventRepository.java
src/main/java/com/kkumteul/domain/event/service/AdminEventService.java
src/main/java/com/kkumteul/exception/AdminEventNotFoundException.java

> #63 
> 등록,수정,삭제,리스트조회, 상세조회 api 구현

Feat: 이벤트 API 구현

---

src/main/java/com/kkumteul/domain/event/controller/AdminEventController.java
src/main/java/com/kkumteul/domain/event/service/AdminEventService.java

> ex) 63
> 관리자 이벤트 서비스 파라미터 수정

Fix: 관리자 이벤트 pathvariable value 명시

---

src/main/java/com/kkumteul/config/SecurityConfig.java
src/main/java/com/kkumteul/domain/book/controller/AdminBookController.java

> ex) #12
> 도서관리 서비스 시큐리티 적용
> 시큐리티 config 파일 내용 변경 (admin -> api/admin/books/**)

Fix :  도서관리 서비스 시큐리티 적용
